spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    prefix: classpath:/templates/

    mvc:
      static-path-pattern: /static/**
    resources:
      static-locations: classpath:/static/


minio:
    bucket: resources
    url: http://localhost:9000
    accessKey: minioadmin
    secretKey: minioadmin


